### ISSUE TITLE
Black Knight shown as black square

### ISSUE THREAD

**Issue by nshram** [MuTsunTsai/fen-tool#3]
This position: k7/1p6/8/1KPqs3/8/8/8/8 generates a diagram where the black knight is showing up as a black square.
(https://mutsuntsai.github.io/fen-tool/gen/?fen=k7/1p6/8/1KPqs3/8/8/8/8&size=26&bg=gray&border=1,2,3&blackWhite&knightOffset=0.625)
![board](https://github.com/MuTsunTsai/fen-tool/assets/1410068/e8877040-d171-408b-a472-2a2016924103)
Changing the BN to a WN or a Neutral Knight also generates a white or white/black square.
The "Copy image URL" and "Save image" options don't have this issue.

**Comment by MuTsunTsai** [comment]
Ah, that is because in the latest update `s` will be reserved for the square symbol. From now the API will always assume the standard FEN (`n` for knight) convention, regardless of whether "S for knight" option is on. You can either change `s` to `n` in the URL, or simply regenerate the code again. Sorry for the breaking changes.
